### ISSUE TITLE
Flatten fails when loading a spec from a local file

### ISSUE THREAD

**Issue by bytheway** [go-openapi/analysis#66]
I created a demo in a repo [here](https://github.com/bytheway/go-openapi-loader-test).

Essentially, when using a local openapi.yaml file:

```
	doc, err := loads.Spec("./openapi.yaml")
	if err != nil {
		log.Fatal(err)
	}
	an := analysis.New(doc.Spec()) // Analyze spec
	err = analysis.Flatten(analysis.FlattenOpts{
		Spec:   an,
		Expand: true,
	})
	if err != nil {
		log.Fatalf("Flatten Failed: %v", err)
	}

```

The call to Flatten fails with:

```
2021/01/26 11:41:38 Flatten Failed: read /Users/bbytheway/tmp/go-openapi-loader-test: is a directory
exit status 1
```

This functionality worked with 

```
	github.com/go-openapi/loads v0.19.7 // indirect
	github.com/go-openapi/strfmt v0.19.6 // indirect
```

but is failing with the latest versions.

**Comment by fredbi** [comment]
I yet have to figure out why this behavior has changed.

It works as expected when you do this:
```go
	err = analysis.Flatten(analysis.FlattenOpts{
		Spec:     an,
		Expand:   true,
		BasePath: doc.SpecFilePath(),
	})
```

**Comment by bytheway** [comment]
That's interesting. Looking at the Flatten code I don't see anywhere in Flatten where an empty BasePath is considered, it looks like it is used and assumed to be populated.

https://github.com/go-openapi/analysis/blob/master/flatten.go#L143

**Comment by gregmarr** [comment]
At L143, if `BasePath` is empty, then the `Join` just produces `cwd`.  So an empty base path means current directory, and a relative path is relative to the `cwd`.  Is `doc` not in the `cwd` in this case?  It looks like it should be, based on the code.

**Comment by bytheway** [comment]
I think that's the problem, it is using the `cwd` and dropping the actual filename, with the error: `read /Users/bbytheway/tmp/go-openapi-loader-test: is a directory`

```
  fmt.Printf("spec path: %v\n", doc.SpecFilePath())
```
produces:
```
spec path: ./openapi.yaml
```

**Comment by fredbi** [comment]
Yes the problem is that the formed URL is invalid because it refers to a folder, not to a document.

To my eyes it seems that this used to work based on some inconsistent internal mangling of paths.
I am currently precisely working on hardening the `spec` package to form valid URLs in all circumstances.

I've tested a tentative fix which forms the following URL for the root document whenever the provided BasePath is empty:
 `file://{cwd}/.root`. With this default, your test program works.

This would work for any `$ref` that is present in the root document, and would work with remote `$ref` that are
either absolute or relative  to docs located in the _current working directory_.

This would obviously fail with a similar program that would, say, load the spec in `../../bytheway/repo/openapi.yaml` from a process which `cwd` is elsewhere.

Another approach could be to explicitly fail and make `BasePath` a requirement, which covers the general case.

In all cases, the default setting introduced by `Flatten()` is unsound and has to go away.

@gregmarr  you might have an opinion / piece of advice here

**Comment by gregmarr** [comment]
I was interpreting `BasePath` as the directory containing the file, and not the file itself, and assuming that the rest of the code used it that way..

**Comment by fredbi** [comment]
Thank you @gregmarr  for sharing your views

>  assuming that the rest of the code used it that way
Well if you look at the go-swagger use of this lib, this appears to me as a document. My understanding of the spec expander (which I am currently working on) tells me that this must be a document.

https://github.com/go-swagger/go-swagger/blob/c1a6d50d1b179d3876139b5428002bb4a391c6bd/generator/spec.go#L78

> it was just luck that it worked before
Yes, this is also my understanding.

However, the call for usability is interesting and could be addressed. My only concern with such "partial solutions" is that a lot of people unwary of this will hit a failure with a strange message such as "xxxx/.root/mypath/tonowhere#definitions" not found...

**Comment by gregmarr** [comment]
>My understanding of the spec expander (which I am currently working on) tells me that this must be a document.

Yes.  My assumption which drove my initial analysis was based solely on looking at the code of that one function and the initial assumption of the report that this wasn't a required parameter.  Both of those assumptions have proven incorrect.

>However, the call for usability is interesting and could be addressed. 

Yes.  If there's a way to make this parameter optional so that anyone who isn't currently providing it will suddenly work without requiring code changes, then that would be good.  It's hard to know how prevalent this usage is.  It's too bad that we can't easily make it a compile-time error to not provide it without changing the API.  At the very least, the documentation of the struct should be updated to indicate that it's required if it can't be made optional.
