### ISSUE TITLE
Flatten object has no key "*OAIGen"

### ISSUE THREAD

**Issue by bir** [go-openapi/analysis#72]
When running flatten with a main swagger file in a sibling directory the path resolution seems to trip on complex references.  In this case the models are a,b,c with the following dependencies:

a -> b
a -> c
b -> c

A,B,C are all in a "definitions" directory.  If the swagger doc is in the parent directly everything works fine, however if in a sibling directory it fails withs:

        	Error Trace:	flatten_test.go:1261
        	Error:      	Received unexpected error:
        	            	at #/paths/~1a/post/responses/200/schema/allOf/0/properties/segment/allOf/1, object has no key "aOAIGen"
        	            	
I modified the TestFlatten_2092 to run the swagger.  In the attached sample, "./swagger.yaml" works fine, but "nested/swagger.yaml" fails.

Sample swaggers attached:
[Archive.zip](https://github.com/go-openapi/analysis/files/6277074/Archive.zip)

**Comment by jackofallops** [comment]
I've noticed this issue also, typically with complex / deep references, seemingly related to some part of the process being non-deterministic? (i.e. manifests somewhat intermittently, and a retry loop around it _usually_ gets a success eventually). I've done _some_ digging, but not managed to pin-point exactly where the problem is. If I get some free time I'll go back to it.

**Comment by fredbi** [comment]
This issue seems to be now outdated.
Here is the result of "swagger flatten" on the provided spec, using latest swagger master (and an older, but recent, release of the analysis package. Seems to me what we would sensibly expect.

The oaigen stuff is used only in last resort cases: this lib tries hard to resolve all possible naming conflicts when bundling the documents.
 
```
swagger flatten swagger.yaml --format=yaml
```
```yaml
schemes:
    - http
swagger: "2.0"
info:
    title: test
    version: "1.0"
paths:
    /a:
        get:
            responses:
                "200":
                    description: OK
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/a'
            operationId: a
        post:
            responses:
                "200":
                    schema:
                        $ref: '#/definitions/a'
                    description: c
            operationId: b
definitions:
    a:
        allOf:
            - type: object
              properties:
                id:
                    type: integer
                segment:
                    $ref: '#/definitions/b'
            - $ref: '#/definitions/c'
        title: a
    b:
        title: b
        allOf:
            - type: object
              properties:
                id:
                    type: integer
            - $ref: '#/definitions/c'
    c:
        type: object
        title: c
        properties:
            updatedBy:
                type: string
```
